[project]
name = "pyLLMZotero"
version = "0.1.0"
description = "A script to retrieve research papers from Zotero, extract keywords using an LLM, and store the processed data into a Neo4j graph database (optional)."
authors = ["Sebastien Gerin <gerin.seb@gmail.com>"]
readme = "README.md"
keywords = ["Zotero", "LLM"]
requires-python = ">=3.11"
dependencies = [
    pyzotero==1.6.8,
    pandas==2.2.3,
    langchain==0.3.7,
    langchain-core==0.3.15,
    langchain-ollama==0.2.0,
    neo4j==5.18.0
]
[project.urls]

